### ISSUE TITLE
User is able to see history of chat messages while they're logged in

### ISSUE THREAD

**Issue by mikairi** [reaper10567/344-Web-Engineering#34]

**Comment by mikairi** [comment]
Unfortunately there's a bug https://github.com/aspnet/EntityFramework/issues/3639 in the version of Entity Framework that we use (beta7) preventing deeply joined select queries. I could not join the Chat table and the Logins/Logouts tables. It seems to be resolved in rc1 but it's too late in the game to update it now. I actually tried updating to rc1 a few days ago and it was just too much work - too many breaking changes.

**Comment by reaper10567** [comment]
lovely. not much we can do about it really though
