### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by reaper10567** [reaper10567/344-Web-Engineering#8]
Calendar Page with the calendar api hookup.

**Comment by reaper10567** [comment]
I am pretty sure this is actually finished.

**Comment by mikairi** [comment]
If the jquery calendar is all we need then I guess it is.

**Comment by reaper10567** [comment]
Yeah, I'm pretty sure this is all we needed

**Comment by reaper10567** [comment]
So imma close this
